-- BANCO DE DADOS DA PIZZARIA

-- CREATE DOMAIN d_nomeProprio VARCHAR(40);
-- CREATE DOMAIN d_telefone VARCHAR(15);
-- CREATE DOMAIN d_moedas DECIMAL(15,2);

CREATE TABLE ingredientes(
idIngrediente SERIAL
);